/*

 Skinny Scroll

 Author: Wesley Luyten
 Version: 1.0 - (2012/07/30)
*/
(function(c){c.SkinnyScroll=function(a,b){var d=SkinnyScroll,c=d.Utils,e=null;this.hasTouch="ontouchstart"in window;this.config={color:"#fff",radius:7,width:7};for(var f in b)this.config[f]=b[f];f="object"===typeof a?a:document.getElementById(a);c.css(f,{overflow:"hidden"});var i=f.children[0];c.css(i,{position:"absolute",left:0,top:0,right:0});this.hasTouch?e=new d.TouchMode(this,f,i):(c.css(i,{overflow:"hidden",bottom:0}),e=new d.MouseMode(this,f,i));e.redraw();c.on(window,"resize",e.redraw);this.scrollTop=
function(a){return e.scrollTop(a)};this.redraw=function(){e.redraw()};this.destroy=function(){c.off(window,"resize",e.redraw);e.destroy()}}})(window);(function(c){c.MouseMode=function(a,b,d){function j(a,b){a.preventDefault?a.preventDefault():a.returnValue=!1;e.scrollTop(e.scrollTop()+20*b)}var e=this,f=new c.Scrollbar(a,b,!0),i=new c.Mousewheel(b);i.on(j);e.scrollTop=function(a){if(void 0===a)return d.scrollTop;d.scrollTop=a;f.setY(d.scrollTop)};e.redraw=function(){f.redraw(d.scrollHeight,d.offsetHeight);e.scrollTop(e.scrollTop())};e.destroy=function(){i.off(j);f.destroy()}}})(SkinnyScroll);(function(c){c.TouchMode=function(a,b,d){function j(){clearInterval(g);d.style.WebkitTransitionDuration="0s"}var e=this,f=new c.Scrollbar(a,b),i="WebKitCSSMatrix"in window,h=i&&"m11"in new WebKitCSSMatrix,g;e.wrap=b;e.view=d;e.x=0;e.y=0;c.Utils.on(d,"touchstart",this);c.Utils.on(d,"webkitTransitionEnd",j);d.style.WebkitTransition="-webkit-transform 1s cubic-bezier(0,0,0.2,1)";e.scrollTop=function(a){if(void 0===a)return this.clampY(),e.y;e.setY(a);f.setY(-a)};e.setY=function(a){d.style.WebkitTransform=
h?"translate3d(0, "+a+"px, 0)":"translate(0, "+a+"px)"};e.getY=function(){if(i){var a=window.getComputedStyle(e.view).webkitTransform;if(a&&"none"!==a)return(new WebKitCSSMatrix(a)).f}return e.y};e.redraw=function(){f.redraw(d.offsetHeight,b.offsetHeight);e.scrollTop(e.scrollTop())};e.destroy=function(){c.Utils.off(d,"touchstart",this);c.Utils.off(d,"webkitTransitionEnd",j);d.style.WebkitTransition="";f.destroy()};e.animateScrollbar=function(){clearInterval(g);g=setInterval(function(){f.setY(-e.getY())},
1E3/30)}};c.TouchMode.prototype={handleEvent:function(a){this[a.type](a)},touchstart:function(a){this.wrap.offsetHeight<this.view.offsetHeight&&(this.moved=!1,this.startX=a.touches[0].pageX-this.x,this.startY=a.touches[0].pageY-this.y,this.view.style.WebkitTransitionDuration="0s",c.Utils.on(this.view,"touchmove",this),c.Utils.on(this.view,"touchend",this))},touchmove:function(a){this.lastX=this.x;this.lastY=this.y;this.x=a.touches[0].pageX-this.startX;this.y=a.touches[0].pageY-this.startY;1===a.touches.length&&
Math.abs(this.y-this.lastY)>Math.abs(this.x-this.lastX)&&(a.preventDefault(),this.moved=!0,this.lastMoveTime=(new Date).getTime(),this.scrollTop(this.y))},touchend:function(a){c.Utils.off(this.view,"touchmove",this);c.Utils.off(this.view,"touchend",this);if(this.moved){a.preventDefault();var a=this.y-this.lastY,b=(new Date).getTime()-this.lastMoveTime+1;this.y+=200*a/b;this.view.style.WebkitTransitionDuration=this.clampY()?"0.5s":"1s";this.setY(this.y);this.animateScrollbar()}},clampY:function(){if(0<=
this.y)return this.y=0,!0;if(this.y<this.wrap.offsetHeight-this.view.offsetHeight)return this.y=this.wrap.offsetHeight-this.view.offsetHeight,!0}}})(SkinnyScroll);(function(c){c.Mousewheel=function(a){var b=this;b.el="object"===typeof a?a:document.getElementById(a);b.calls=[];b.t=function(a){b.to(a)}};c.Mousewheel.prototype={on:function(a){if(0===this.calls.length)c.Utils.on(this.el,"DOMMouseScroll mousewheel",this.t);this.calls.push(a)},off:function(a){if(a)for(var b=0;b<this.calls.length;b++)this.calls[b]===a&&(this.calls.splice(b,1),b--);else this.calls=[];0===this.calls.length&&c.Utils.off(this.el,"DOMMouseScroll mousewheel",this.t)},to:function(a){var a=
a||window.event,b=0;a.wheelDelta&&(b=-a.wheelDelta/120);a.detail&&(b=a.detail/3);var d=[].slice.call(arguments,1);d.unshift(a,b);for(b=0;b<this.calls.length;b++)"function"===typeof this.calls[b]&&this.calls[b].apply(this,d)}}})(SkinnyScroll);(function(c){c.Scrollbar=function(a,b,d){function j(a){a=a||window.event;i(a);a.preventDefault&&a.preventDefault();h.on(document,"mousemove",e);h.on(document,"mouseup",f);h.on(g.hand,"mouseup",f);g.diff=a.pageY-g.hand.offsetTop}function e(b){b=b||window.event;i(b);a.scrollTop((b.pageY-g.diff)*g.ratio);return!1}function f(){h.off(document,"mousemove",e);h.off(document,"mouseup",f);h.off(g.hand,"mouseup",f)}function i(a){if(void 0===a.pageX&&void 0!==a.clientX){var b=document.documentElement,d=document.body;
a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}}var h=c.Utils,g=this,k=a.config.color,l=a.config.radius,m=a.config.width,b="object"===typeof b?b:document.getElementById(b);g.rail=h.add("div",b,{position:"absolute",right:2,top:2,bottom:2,width:m,zIndex:90});g.rail.className="skinnyscrollbar";g.back=h.add("div",g.rail,{backgroundColor:k,filter:"alpha(opacity=15)",
opacity:0.15,borderRadius:l,position:"absolute",left:0,top:0,right:0,bottom:0});g.hand=h.add("div",g.rail,{backgroundColor:k,filter:"alpha(opacity=25)",opacity:0.25,borderRadius:l,position:"absolute",left:0,top:0,width:m,height:7});g.diff=h.getOffset(g.hand).top;d&&(h.on(g.hand,"mousedown",j),h.on(g.rail,"mousedown",e))};c.Scrollbar.prototype={redraw:function(a,b){this.rail.style.display=b>=a?"none":"block";this.scrollHeight=a;this.height=b;this.handHeight=Math.max(b/a*this.rail.offsetHeight,25);
this.ratio=(a-b)/(this.rail.offsetHeight-this.handHeight)},destroy:function(){var a=this.rail.parentNode;a&&a.removeChild(this.rail)},setY:function(a){var b=a/this.ratio;isNaN(b)&&(b=0);var d=b+this.handHeight-this.rail.offsetHeight,c=this.hand.style;0>a?(c.height=Math.max(this.handHeight+b,25)+"px",c.top="0px"):0<d?(c.height=Math.max(this.handHeight-d,25)+"px",c.bottom="0px",c.top="auto"):(c.height=this.handHeight+"px",c.top=b+"px")}}})(SkinnyScroll);(function(c){c.Utils=function(){};c.Utils.add=function(a,b,d){a=document.createElement(a);b.appendChild(a);c.Utils.css(a,d);return a};c.Utils.css=function(a,b){if(a)for(var d in b)if("undefined"!==typeof b[d]){if("number"==typeof b[d]&&!("zIndex"==d||"opacity"==d)){if(isNaN(b[d]))continue;b[d]=Math.ceil(b[d])+"px"}try{a.style[d]=b[d]}catch(c){}}};c.Utils.getOffset=function(a){for(var b=0,d=0;a&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)b+=a.offsetLeft-a.scrollLeft,d+=a.offsetTop-a.scrollTop,a=a.offsetParent;
return{top:d,left:b}};c.Utils.on=function(a,b,d){if(!(null===a||void 0===a))for(var b=b.split(" "),c=0;c<b.length;c++)a.addEventListener?a.addEventListener(b[c],d,!1):a.attachEvent?a.attachEvent("on"+b[c],d):a["on"+b[c]]=d};c.Utils.off=function(a,b,d){if(!(null===a||void 0===a))for(var b=b.split(" "),c=0;c<b.length;c++)a.removeEventListener?a.removeEventListener(b[c],d,!1):a.detachEvent?a.detachEvent("on"+b[c],d):a["on"+b[c]]=null}})(SkinnyScroll);
